
[[redirects]]
  from = "/soap?service=PhilhealthService"
  to = "https://eclaimstest2.philhealth.gov.ph:8077/soap?service=PhilhealthService"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"